const phrases = [
  { kor: "안녕하세요", ar: "مرحباً", en: "Hello" },
  { kor: "감사합니다", ar: "شكراً", en: "Thank you" },
  { kor: "죄송합니다", ar: "آسف", en: "Sorry" },
  { kor: "네", ar: "نعم", en: "Yes" },
  { kor: "아니요", ar: "لا", en: "No" },
  { kor: "잘 지내세요?", ar: "هل أنت بخير؟", en: "How are you?" },
  { kor: "이름이 뭐예요?", ar: "ما اسمك؟", en: "What is your name?" },
  { kor: "저는 ... 입니다", ar: "أنا ...", en: "I am ..." },
  { kor: "어디에 가요?", ar: "إلى أين تذهب؟", en: "Where are you going?" },
  { kor: "얼마예요?", ar: "كم الثمن؟", en: "How much is it?" },
  { kor: "화장실 어디에 있어요?", ar: "أين الحمام؟", en: "Where is the bathroom?" },
  { kor: "도와주세요!", ar: "ساعدني!", en: "Help me!" },
  { kor: "이해하지 못해요", ar: "لا أفهم", en: "I don't understand" },
  { kor: "천천히 말해 주세요", ar: "تحدث ببطء من فضلك", en: "Please speak slowly" },
  { kor: "한국어를 배워요", ar: "أنا أتعلم الكورية", en: "I am learning Korean" },
  { kor: "좋은 하루 보내세요", ar: "أتمنى لك يوماً سعيداً", en: "Have a good day" },
  { kor: "잘 자요", ar: "تصبح على خير", en: "Good night" },
  { kor: "밥 먹었어요?", ar: "هل أكلت؟", en: "Have you eaten?" },
  { kor: "친구가 많아요", ar: "لدي الكثير من الأصدقاء", en: "I have many friends" },
  { kor: "사진 찍어 주세요", ar: "من فضلك، التقط صورة", en: "Please take a picture" },
  { kor: "지금 몇 시예요?", ar: "كم الساعة الآن؟", en: "What time is it now?" },
  { kor: "밖에 비가 와요", ar: "إنها تمطر في الخارج", en: "It's raining outside" },
  { kor: "오늘 날씨 어때요?", ar: "كيف الطقس اليوم؟", en: "How is the weather today?" },
  { kor: "영화를 보고 싶어요", ar: "أريد أن أشاهد فيلمًا", en: "I want to watch a movie" },
  { kor: "음식을 좋아해요", ar: "أحب الطعام", en: "I like food" },
  { kor: "커피 마실래요?", ar: "هل تريد أن تشرب قهوة؟", en: "Do you want to drink coffee?" },
  { kor: "집에 가요", ar: "أنا ذاهب إلى البيت", en: "I'm going home" },
  { kor: "병원에 가야 해요", ar: "يجب أن أذهب إلى المستشفى", en: "I need to go to the hospital" },
  { kor: "전화번호가 뭐예요?", ar: "ما رقم هاتفك؟", en: "What is your phone number?" },
  { kor: "축하합니다!", ar: "مبروك!", en: "Congratulations!" },
  { kor: "생일 축하해요", ar: "عيد ميلاد سعيد", en: "Happy birthday" },
  { kor: "지금 어디에 있어요?", ar: "أين أنت الآن؟", en: "Where are you now?" },
  { kor: "음악을 좋아해요", ar: "أحب الموسيقى", en: "I like music" },
  { kor: "내일 만나요", ar: "أراك غداً", en: "See you tomorrow" },
  { kor: "무슨 일이에요?", ar: "ما المشكلة؟", en: "What's the matter?" },
  { kor: "열심히 공부해요", ar: "ادرس بجد", en: "Study hard" },
  { kor: "도서관에 가요", ar: "أنا ذاهب إلى المكتبة", en: "I am going to the library" },
  { kor: "운동하러 가요", ar: "أنا ذاهب للتمرين", en: "I'm going to exercise" },
  { kor: "친구를 만나고 싶어요", ar: "أريد لقاء الأصدقاء", en: "I want to meet friends" },
  { kor: "한국 음식이 맛있어요", ar: "الطعام الكوري لذيذ", en: "Korean food is delicious" },
  { kor: "여기 앉아도 돼요?", ar: "هل يمكنني الجلوس هنا؟", en: "Can I sit here?" },
  { kor: "조용히 해 주세요", ar: "من فضلك، كن هادئاً", en: "Please be quiet" },
  { kor: "사진을 보고 싶어요", ar: "أريد رؤية الصور", en: "I want to see the photos" },
  { kor: "영어 할 수 있어요?", ar: "هل تستطيع التحدث بالإنجليزية؟", en: "Can you speak English?" },
  { kor: "계산서 주세요", ar: "من فضلك، الحساب", en: "Please give me the bill" },
  { kor: "이거 맛있어요", ar: "هذا لذيذ", en: "This is delicious" },
  { kor: "어디서 왔어요?", ar: "من أين أنت؟", en: "Where are you from?" },
  { kor: "좋아요", ar: "جيد", en: "Good" },
  { kor: "싫어요", ar: "لا أحب", en: "I don't like" },
  { kor: "괜찮아요", ar: "لا بأس", en: "It's okay" },
  { kor: "도와줄게요", ar: "سأساعدك", en: "I will help you" },
  { kor: "얼마나 걸려요?", ar: "كم يستغرق؟", en: "How long does it take?" },
  { kor: "문 좀 열어 주세요", ar: "من فضلك، افتح الباب", en: "Please open the door" },
  { kor: "문 좀 닫아 주세요", ar: "من فضلك، أغلق الباب", en: "Please close the door" },
  { kor: "길을 잃었어요", ar: "لقد ضعت", en: "I am lost" },
  { kor: "택시 불러 주세요", ar: "من فضلك، استدعي تاكسي", en: "Please call a taxi" },
  { kor: "얼굴이 예뻐요", ar: "وجهك جميل", en: "Your face is pretty" },
  { kor: "몸이 아파요", ar: "أنا مريض", en: "I feel sick" },
  { kor: "조심하세요", ar: "احذر", en: "Be careful" },
  { kor: "즐거운 여행 되세요", ar: "رحلة سعيدة", en: "Have a pleasant trip" },
  { kor: "이해했어요", ar: "فهمت", en: "I understood" },
  { kor: "무슨 뜻이에요?", ar: "ماذا يعني هذا؟", en: "What does it mean?" },
  { kor: "천천히 하세요", ar: "افعلها ببطء", en: "Take your time" },
  { kor: "힘내세요", ar: "تشجع", en: "Cheer up" },
  { kor: "배고파요", ar: "أنا جائع", en: "I am hungry" },
  { kor: "목말라요", ar: "أنا عطشان", en: "I am thirsty" },
  { kor: "너무 좋아요", ar: "إنه جيد جداً", en: "It's very good" },
  { kor: "화이팅!", ar: "حظاً موفقاً!", en: "Fighting!" },
  { kor: "기다려 주세요", ar: "انتظر من فضلك", en: "Please wait" },
  { kor: "문제가 있어요", ar: "هناك مشكلة", en: "There is a problem" },
  { kor: "약을 먹었어요?", ar: "هل تناولت الدواء؟", en: "Did you take medicine?" },
  { kor: "빨리 와 주세요", ar: "تعال بسرعة من فضلك", en: "Please come quickly" },
  { kor: "휴대전화가 어디에 있어요?", ar: "أين هاتفك المحمول؟", en: "Where is your phone?" },
  { kor: "컴퓨터가 고장 났어요", ar: "الحاسوب معطل", en: "The computer is broken" },
  { kor: "공부를 시작해요", ar: "سأبدأ الدراسة", en: "I will start studying" },
  { kor: "영화를 좋아해요", ar: "أحب الأفلام", en: "I like movies" },
  { kor: "한국에 가고 싶어요", ar: "أريد الذهاب إلى كوريا", en: "I want to go to Korea" },
  { kor: "운전할 수 있어요?", ar: "هل تستطيع القيادة؟", en: "Can you drive?" },
  { kor: "지금 바빠요", ar: "أنا مشغول الآن", en: "I am busy now" },
  { kor: "쉬고 싶어요", ar: "أريد أن أرتاح", en: "I want to rest" },
  { kor: "공원에 가요", ar: "أنا ذاهب إلى الحديقة", en: "I am going to the park" },
  { kor: "좋은 친구예요", ar: "إنه صديق جيد", en: "He/She is a good friend" },
  { kor: "음식 주문할게요", ar: "سأطلب الطعام", en: "I will order food" },
  { kor: "이거 얼마예요?", ar: "كم ثمن هذا؟", en: "How much is this?" },
  { kor: "저기요!", ar: "عفواً!", en: "Excuse me!" },
  { kor: "사진 좀 찍어 주세요", ar: "من فضلك، التقط صورة", en: "Please take a picture" },
  { kor: "도서관 조용히 해 주세요", ar: "من فضلك، كن هادئاً في المكتبة", en: "Please be quiet in the library" },
  { kor: "나는 학생입니다", ar: "أنا طالب", en: "I am a student" },
  { kor: "한국어를 잘 못해요", ar: "أنا لا أتحدث الكورية جيداً", en: "I don't speak Korean well" },
  { kor: "영어를 배우고 싶어요", ar: "أريد تعلم الإنجليزية", en: "I want to learn English" },
  { kor: "계단을 이용하세요", ar: "استخدم السلم", en: "Use the stairs" },
  { kor: "비행기가 지연되었어요", ar: "تأخر الطائرة", en: "The plane is delayed" },
  { kor: "열차가 도착했어요", ar: "وصل القطار", en: "The train has arrived" },
  { kor: "날씨가 추워요", ar: "الطقس بارد", en: "The weather is cold" },
  { kor: "친절하게 대해 주세요", ar: "كن لطيفاً من فضلك", en: "Please be kind" },
  { kor: "교통이 복잡해요", ar: "المرور مزدحم", en: "Traffic is congested" },
  { kor: "은행은 어디에 있어요?", ar: "أين البنك؟", en: "Where is the bank?" },
  { kor: "식당 예약했어요", ar: "حجزت مطعماً", en: "I made a reservation at a restaurant" },
  { kor: "이쪽으로 오세요", ar: "تعال من هنا", en: "Come this way" },
  { kor: "어디서 만날까요?", ar: "أين نلتقي؟", en: "Where shall we meet?" },
  { kor: "도와줘서 고마워요", ar: "شكراً للمساعدة", en: "Thank you for helping me" },
  { kor: "안전을 위해 조심하세요", ar: "احذر من أجل السلامة", en: "Be careful for safety" },
  { kor: "전화를 끊었어요", ar: "أنهيت المكالمة", en: "I hung up the phone" },
  { kor: "수고하셨습니다", ar: "شكراً على مجهودك", en: "Thank you for your effort" },
  { kor: "바쁘시면 말씀하세요", ar: "أخبرني إذا كنت مشغولاً", en: "Let me know if you're busy" },
  { kor: "여기요!", ar: "من فضلك!", en: "Excuse me!" },
  { kor: "조금 더 주세요", ar: "أعطني المزيد قليلاً", en: "Give me a little more" },
  { kor: "빨리 와 주세요", ar: "تعال بسرعة من فضلك", en: "Please come quickly" },
  { kor: "친구랑 여행 갈 거예요", ar: "سأسافر مع أصدقائي", en: "I will travel with my friends" },
  { kor: "한국어 공부가 재미있어요", ar: "دراسة الكورية ممتعة", en: "Studying Korean is fun" },
  { kor: "음식을 조심하세요", ar: "احذر من الطعام", en: "Be careful with the food" },
  { kor: "좋은 하루 되세요", ar: "أتمنى لك يومًا سعيدًا", en: "Have a nice day" }
];
